<?xml version="1.0"?>
<robot name="my_robot" xmlns:xacro="http://www.ros.org/wiki/xacro">


    <xacro:property name = "camera_width" value="0.1"/>
    <xacro:property name = "camera_length" value="0.01"/>
    <xacro:property name = "camera_height" value="0.05"/>

    <link name="camera_link">
     <visual>
        <geometry>
            <box size="${camera_length} ${camera_width}  ${camera_height}"/> 
        </geometry>
        <origin xyz="0 0 0" rpy="0 0 0"/>
        <material name="black"/>
     </visual>
     <collision>
        <geometry>
            <box size="${camera_length} ${camera_width}  ${camera_height}"/> 
        </geometry>
        <origin xyz="0 0 0" rpy="0 0 0"/>
     </collision>
     <xacro:box_inertia m = "0.5" l="${2*camera_length}" 
                                  w="${2*camera_width}" 
                                  h = "${2*camera_height}"
                                  xyz = "0 0 0"
                                  rpy = "0 0 0" />
    </link>

    <joint name="base_camera_joint" type="fixed">
        <parent link="base_link"/>
        <child link="camera_link"/>
        <origin xyz="0.3 0 0" rpy="0 0 0"/>
    </joint>

    <gazebo reference= "camera_link">
        <material>Gazebo/Grey</material>
        <sensor name="camera_sensor" type="camera">
            <pose> 0 0 0 0 0 0 </pose>
            <visualize>true</visualize>
            <update_rate>10.0</update_rate>

            <plugin name="camera_controller" filename = "libgazebo_ros_camera.so">
                <frame_name>camera_link</frame_name>
            </plugin>

        </sensor>
    </gazebo>
    
</robot>