<?xml version="1.0"?>
<robot name="my_robot" xmlns:xacro="http://www.ros.org/wiki/xacro">


    <xacro:property name = "lidar_radius" value="0.08"/>
    <xacro:property name = "lidar_length" value="0.05"/>
    <!-- <xacro:property name = "camera_height" value="0.05"/> -->

    <link name="lidar_link">
        <visual>
            <geometry>
                <cylinder radius="${lidar_radius}" length="${lidar_length}"/> 
            </geometry>
            <origin xyz="0 0 0" rpy="0 0 0"/>
            <material name="grey"/>
        </visual> 

        <collision>
            <geometry>
                <cylinder radius="${lidar_radius}" length="${lidar_length}"/> 
            </geometry>
            <origin xyz="0 0 0" rpy="0 0 0"/>
        </collision>

        <xacro:cylinder_inertia m = "0.2" r="${2*lidar_radius}" 
                                          h="${2*lidar_length}" 
                                          xyz = "0 0 0"
                                          rpy = "0 0 0" />
        </link>

    <joint name="base_lidar_joint" type="fixed">
        <parent link="base_link"/>
        <child link="lidar_link"/>
        <origin xyz="0 0 ${(base_height / 2) + (lidar_length / 2)}" rpy="0 0 0"/>
    </joint>

    <gazebo reference= "lidar_link">
        <material>Gazebo/Grey</material>
        <sensor name="lidar_sensor" type="ray">
            <pose> 0 0 0 0 0 0 </pose>
            <visualize>true</visualize>
            <update_rate>10.0</update_rate>

            <ray>
                <scan>
                    <horizontal>
                        <samples>720</samples>
                        <resolution>1</resolution>
                        <min_angle>3.14</min_angle>
                        <max_angle>3.14</max_angle>
                    </horizontal>
                </scan>
                <range>
                    <min>0.1</min>
                    <max>30.0</max>
                    <resolution>0.01</resolution>
                </range>
            </ray>

            <plugin name="lidar" filename = "libgazebo_ros_ray_sensor.so">
                <output_type>sensor_msgs/LaserScan</output_type>
            </plugin>

        </sensor>
    </gazebo>
    
</robot>